### ISSUE TITLE
你好，我有些疑问

### ISSUE THREAD

**Issue by zhangslob** [thsheep/scrapy_redis_cluster#1]
这个是用来解决redis内存占用空间过大的问题吗？
使用多台redis机器代替单台？

**Comment by thsheep** [comment]
面临单机内存的不足 就是使用布隆去重 内存还是不足的尴尬？ 你需要这个：

https://github.com/thsheep/scrapy_redis_cluster

**Comment by zhangslob** [comment]
redis内存虽然小，可以用mongo储存啊。
